### ISSUE TITLE
Move to Jekyll

### ISSUE THREAD

**Issue by trevorsenior** [emcenrue/MobileAppDevelopmentClubWebsite#6]
GitHub supports Jekyll with GitHub pages. It is a static site
generator that would remove the need for manually editing the HTML
when updates are needed.

Also, by switching to Jekyll it will facilitate blog posts / entries
that can serve as a good introduction to git & working with others
should members wish to contribute a post here and there about the
projects that they are working on.

If this is something you are interested in, I can work on this and
make a PR.

**Comment by emcenrue** [comment]
Word?! Yea that would be super awesome! I guess I'll see you tomorrow night if you want to discuss anything about it

:shipit: :shipit: :shipit:  :+1: :8ball: :100:

**Comment by trevorsenior** [comment]
Moved to: https://github.com/MandWdevclub/MandWdevclub.github.io
